name: "FIVES512"
description: "FIVES dataset at 512x512 resolution"

paths:
  root: "data/FIVES512"
  train: "data/FIVES512/train"
  val: "data/FIVES512/val"
  test: "data/FIVES512/test"

image_size: [512, 512]
num_channels: 3
num_classes: 1

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225] 